### ISSUE TITLE
Batch retrieve catalog objects returns out of order

### ISSUE THREAD

**Issue by kyeshmz** [square/square-nodejs-sdk#153] opened 2024-07-29 05:11 UTC
**Describe the bug**
 /v2/catalog/batch-retrieve returns results out of order

**Expected behavior**
Return the same order as the given array.

**To Reproduce**
Steps to reproduce the bug:
1. Create array
2. Call batch retrieve API through sdk
3. Check result order

**Square SDK version**
square": "^37.1.1",

**Additional context**

**Comment by zenmasterjobo** [comment] 2024-07-29 18:11
hi @kyeshmz 

This is currently the expected outcome for this API. Curious what your use case is that you are concerned about the response order? I can take the feedback to the team that owns this API. 

I will be closing this issue though, as it's not a bug, nor is it a a problem with the SDK - this is at the API level.

Thank you!

**Closed by zenmasterjobo** 2024-07-29 18:11 UTC

**Comment by kyeshmz** [comment] 2024-07-31 08:55
@zenmasterjobo  I am using the order of the IDs to guarantee a certain order for the front end. Without this, a user would have to manage an ordinal number to determine how they want a certain item to appear.
